import type { AppLanguage } from "@/contexts/I18nContext";

const KO_SAMPLE = [
  "# Markdown Editor 이렇게 써보세요",
  "",
  "이 편집기는 **실시간 프리뷰**를 지원하는 마크다운 편집기입니다. 왼쪽에 마크다운을 작성하면 오른쪽에서 즉시 결과를 확인할 수 있습니다.",
  "",
  "## 기본 문법",
  "",
  "### 텍스트 스타일링",
  "",
  "**굵은 텍스트**, *기울임 텍스트*, ~~취소선~~을 사용할 수 있습니다.",
  "",
  "인라인 코드는 `console.log(\"Hello\")`처럼 작성합니다.",
  "",
  "### 링크와 이미지",
  "",
  "[GitHub](https://github.com)에 방문해보세요.",
  "",
  "### 인용문",
  "",
  "> 좋은 코드는 최고의 문서입니다.",
  "> 대부분의 경우 주석이 필요하지 않습니다.",
  "> — Steve McConnell",
  "",
  "### 리스트",
  "",
  "**순서 없는 리스트:**",
  "- 첫 번째 항목",
  "- 두 번째 항목",
  "  - 중첩 항목",
  "  - 또 다른 중첩 항목",
  "- 세 번째 항목",
  "",
  "**순서 있는 리스트:**",
  "1. 프로젝트 설정",
  "2. 코드 작성",
  "3. 테스트 실행",
  "4. 배포",
  "",
  "### 코드 블록",
  "",
  "```javascript",
  "function greet(name) {",
  "  return `안녕하세요, ${name}님!`;",
  "}",
  "",
  "console.log(greet(\"세계\"));",
  "```",
  "",
  "### 표",
  "",
  "| 기능 | 단축키 | 설명 |",
  "|------|--------|------|",
  "| 저장 | Ctrl+S | 자동 저장됨 |",
  "| 다운로드 | - | MD 파일 다운로드 |",
  "| 테마 | - | 다크/라이트 전환 |",
  "",
  "### 체크리스트",
  "",
  "- [x] 마크다운 편집기 만들기",
  "- [x] 실시간 프리뷰 추가",
  "- [x] 다크 모드 지원",
  "- [ ] 더 많은 기능 추가하기",
  "",
  "---",
  "",
  "*이 내용을 자유롭게 수정하고 마크다운의 다양한 기능을 시험해보세요!*",
].join("\n");

const EN_SAMPLE = [
  "# Markdown Editor Quick Start",
  "",
  "This editor provides a **live markdown preview**. Write markdown on the left and see the rendered result instantly on the right.",
  "",
  "## Basic Syntax",
  "",
  "### Text Styling",
  "",
  "Use **bold**, *italic*, and ~~strikethrough~~ styles.",
  "",
  "Inline code looks like `console.log(\"Hello\")`.",
  "",
  "### Links and Images",
  "",
  "Visit [GitHub](https://github.com).",
  "",
  "### Quotes",
  "",
  "> Good code is the best documentation.",
  "> Most of the time, comments are unnecessary.",
  "> — Steve McConnell",
  "",
  "### Lists",
  "",
  "**Unordered list:**",
  "- First item",
  "- Second item",
  "  - Nested item",
  "  - Another nested item",
  "- Third item",
  "",
  "**Ordered list:**",
  "1. Set up project",
  "2. Write code",
  "3. Run tests",
  "4. Deploy",
  "",
  "### Code Block",
  "",
  "```javascript",
  "function greet(name) {",
  "  return `Hello, ${name}!`;",
  "}",
  "",
  "console.log(greet(\"world\"));",
  "```",
  "",
  "### Table",
  "",
  "| Feature | Shortcut | Description |",
  "|---------|----------|-------------|",
  "| Save | Ctrl+S | Auto-saved |",
  "| Download | - | Download MD file |",
  "| Theme | - | Toggle dark/light |",
  "",
  "### Checklist",
  "",
  "- [x] Build markdown editor",
  "- [x] Add live preview",
  "- [x] Support dark mode",
  "- [ ] Add more features",
  "",
  "---",
  "",
  "*Feel free to edit this content and explore markdown features!*",
].join("\n");

export const SAMPLE_MARKDOWN_BY_LANGUAGE: Record<AppLanguage, string> = {
  ko: KO_SAMPLE,
  en: EN_SAMPLE,
};

export function getSampleMarkdown(language: AppLanguage): string {
  return SAMPLE_MARKDOWN_BY_LANGUAGE[language];
}

export const SAMPLE_MARKDOWN = KO_SAMPLE;
